services:
  cluster:
    image: ghcr.io/zerocluster/cluster
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

    command: run

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

networks:
  network: ~
