#!/usr/bin/env -S docker stack deploy --with-registry-auth core -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml core

services:
  core:
    image: ghcr.io/zerocluster/core
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

    command: ""

    networks: [main]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

networks:
  main: { external: true }

x-build:
  default_tag: latest
  auto_tags: [main, latest, next]
